version: '3.1'

services:
  db:
    container_name: mymysql
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: HsbotDb  # 修改密码为HsbotDb
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data: